### ISSUE TITLE
Highscores | La liste ne doit contenir que 10 scores

### ISSUE THREAD

**Issue by nicolaschenet** [stephane71/da-movie-quizz#1]
- [x] Limiter la liste à 10 highscores
- [x] Mettre à jour les critères de demande de nom du joueur

**Comment by stephane71** [comment]
La liste est a présent limité à 10 highscores: https://github.com/stephane71/da-movie-quizz/commit/e2d35848a0f3cd913d17fc7b70de74c5e5ca86fb
On propose d'enregistrer le highscore du joueur 
- si le score est != 0
- sinon si il y a moins de 10 highscores d'enregistrés
- sinon si le score est > à au moins 1 highscore

**Comment by nicolaschenet** [comment]
Je check ça en arrivant au bureau. Merci !
